### ISSUE TITLE
报空指针异常

### ISSUE THREAD

**Issue by liliuchen** [crazycodeboy/TakePhoto#13]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1007, result=-1, data=Intent { dat=file:///storage/emulated/0/DCIM/Camera/IMG_20160814_162224_HDR.jpg typ=image/jpeg }} to activity 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.startActivityForResult(android.content.Intent, int)' on a null object reference
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3706)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749)
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:153)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.startActivityForResult(android.content.Intent, int)' on a null object reference
                                                                         at com.soundcloud.android.crop.Crop.start(Crop.java:151)
                                                                         at com.soundcloud.android.crop.Crop.start(Crop.java:128)
                                                                         at com.jph.takephoto.uitl.TUtils.cropWithOwnApp(TUtils.java:102)
                                                                         at com.jph.takephoto.app.TakePhotoImpl.onCrop(TakePhotoImpl.java:195)
                                                                         at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:87)
                                                                         at com.jph.takephoto.app.TakePhotoFragmentActivity.onActivityResult(TakePhotoFragmentActivity.java:27)
                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6508)
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3702)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3749) 
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by crazycodeboy** [comment]
做的什么操作呢？

**Comment by liliuchen** [comment]
getTakePhoto().onEnableCompress(compressConfig,true).onPickFromCaptureWithCrop(imageUri,cropOptions);

**Comment by liliuchen** [comment]
不做剪切正常，剪切就报空指针，我的是小米手机

**Comment by crazycodeboy** [comment]
你的cropOptions传的是什么？

原始邮件
发件人:bluce leenotifications@github.com
收件人:crazycodeboy/TakePhotoTakePhoto@noreply.github.com
抄送:Jia PengHuicrazycodeboy@gmail.com; Commentcomment@noreply.github.com
发送时间:2016年8月19日(周五) 18:33
主题:Re: [crazycodeboy/TakePhoto] 报空指针异常 (#13)


不做剪切正常，剪切就报空指针，我的是小米手机

**Comment by liuz430524** [comment]
CropOptions 配置为：
`CropOptions cropOptions = new CropOptions.Builder().setAspectX(1).setAspectY(1).setWithOwnCrop(true).create();`
选setWithOwnCrop(true)使用自带裁剪工具就会报空指针错误，和一楼错误一样，设为false用系统的没问题。
![default](https://cloud.githubusercontent.com/assets/8044101/17879103/92f0e5ec-6921-11e6-8444-fb4132365d5a.PNG)
手机是华为p6(Android 4.4.2)，已申请读写SD卡的权限。
@crazycodeboy 工具很方便，辛苦了
