### ISSUE TITLE
选择某种图片报错（什么类型的图片还未知）

### ISSUE THREAD

**Issue by caixiaoxu** [crazycodeboy/TakePhoto#130]
UploadTaskPicActivity}: java.lang.reflect.UndeclaredThrowableException
01-11 15:45:39.205 4478-4478/W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3622)
01-11 15:45:39.205 4478-4478/W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3665)
01-11 15:45:39.205 4478-4478/W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:139)
01-11 15:45:39.205 4478-4478/W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
01-11 15:45:39.210 4478-4478/W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 15:45:39.210 4478-4478/W/System.err:     at android.os.Looper.loop(Looper.java:136)
01-11 15:45:39.210 4478-4478/W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5314)
01-11 15:45:39.210 4478-4478/W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-11 15:45:39.210 4478-4478/W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
01-11 15:45:39.210 4478-4478/W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-11 15:45:39.210 4478-4478/W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
01-11 15:45:39.210 4478-4478/W/System.err:     at $Proxy0.onActivityResult(Native Method)
01-11 15:45:39.210 4478-4478/W/System.err:     at .activity.Order.UploadTaskPicActivity.onActivityResult(UploadTaskPicActivity.java:91)
01-11 15:45:39.210 4478-4478/W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:5507)
01-11 15:45:39.210 4478-4478/W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3618)
01-11 15:45:39.210 4478-4478/W/System.err: 	... 11 more
01-11 15:45:39.210 4478-4478/W/System.err: Caused by: java.lang.reflect.InvocationTargetException
01-11 15:45:39.210 4478-4478/W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-11 15:45:39.210 4478-4478/W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
01-11 15:45:39.210 4478-4478/W/System.err: 	... 15 more
01-11 15:45:39.210 4478-4478/W/System.err: Caused by: java.lang.NullPointerException
01-11 15:45:39.210 4478-4478/W/System.err:     at com.jph.takephoto.uitl.TImageFiles.getMimeType(TImageFiles.java:133)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.jph.takephoto.uitl.TImageFiles.getTempFile(TImageFiles.java:96)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.jph.takephoto.uitl.TUriParse.getFilePathWithDocumentsUri(TUriParse.java:143)
01-11 15:45:39.210 4478-4478/W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:141)
01-11 15:45:39.210 4478-4478/W/System.err: 	... 18 more

**Comment by UserName-Haha** [comment]
朋友，我也遇到这个问题了，后来解决了，这个是由于图片格式不支持导致的，添加个try catch就好了
