### ISSUE TITLE
android 7.0 跑测试demo未作任何更改报错

### ISSUE THREAD

**Issue by chengyang225** [crazycodeboy/TakePhoto#148]
成功运行,然后裁切选择否,压缩选择否,然后进入系统相册选择单张图片报错,完整日志如下:
02-15 05:27:11.395 27056-27056/com.jph.simple E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.jph.simple, PID: 27056
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jph.simple/com.jph.simple.ResultActivity}: java.lang.NullPointerException
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                    at android.os.Looper.loop(Looper.java:203)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6251)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
                                                                 Caused by: java.lang.NullPointerException
                                                                    at java.io.File.<init>(File.java:262)
                                                                    at com.jph.simple.ResultActivity.showImg(ResultActivity.java:59)
                                                                    at com.jph.simple.ResultActivity.onCreate(ResultActivity.java:44)
                                                                    at android.app.Activity.performCreate(Activity.java:6666)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:203) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6251) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by crazycodeboy** [comment]
下载Demo试一下：[Demo](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)
