### ISSUE TITLE
魅族Pro6，选择图片之后，直接crash

### ISSUE THREAD

**Issue by Demarcia-cn** [crazycodeboy/TakePhoto#168]
DISPLAY=Flyme 6.0.2.0A
MODEL=PRO 6
DEVICE=PRO6
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.***.****/com.soundcloud.android.crop.CropImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5963)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at android.content.ContentResolver.checkLeakDetectIgnoreList(ContentResolver.java:2703)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1186)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:966)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:686)
	at com.soundcloud.android.crop.CropImageActivity.calculateBitmapSampleSize(Unknown Source)
	at com.soundcloud.android.crop.CropImageActivity.loadInput(Unknown Source)
	at com.soundcloud.android.crop.CropImageActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6373)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at android.content.ContentResolver.checkLeakDetectIgnoreList(ContentResolver.java:2703)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1186)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:966)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:686)
	at com.soundcloud.android.crop.CropImageActivity.calculateBitmapSampleSize(Unknown Source)
	at com.soundcloud.android.crop.CropImageActivity.loadInput(Unknown Source)
	at com.soundcloud.android.crop.CropImageActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6373)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5963)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

**Comment by Demarcia-cn** [comment]
看了一下日志，貌似是那个第三方截图的问题。
