### ISSUE TITLE
锤子手机，压缩配置-->是否压缩选择否时会报错

### ISSUE THREAD

**Issue by gaoshanliushui662** [crazycodeboy/TakePhoto#177]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jph.simple/com.jph.simple.ResultActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:160)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5371)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                  at java.io.File.fixSlashes(File.java:185)
                                                                  at java.io.File.<init>(File.java:134)
                                                                  at com.jph.simple.ResultActivity.showImg(ResultActivity.java:59)
                                                                  at com.jph.simple.ResultActivity.onCreate(ResultActivity.java:44)
                                                                  at android.app.Activity.performCreate(Activity.java:6102)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:160) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5371) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by Onionsss** [comment]
解决了吗 我也是这个问题
