### ISSUE TITLE
打开相机报错

### ISSUE THREAD

**Issue by shunanlove** [crazycodeboy/TakePhoto#189]
Process: com.nowbook.minan, PID: 24604
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nowbook.minan/com.imagepicker.PhotoPickerActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2688)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:160)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                                    Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                       at $Proxy8.onPickFromCapture(Unknown Source)
                                                                       at com.imagepicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:43)
                                                                       at android.app.Activity.performCreate(Activity.java:6736)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                       at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:160) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6200) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                       at $Proxy8.onPickFromCapture(Unknown Source) 
                                                                       at com.imagepicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:43) 
                                                                       at android.app.Activity.performCreate(Activity.java:6736) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                       at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:160) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6200) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
                                                                    Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/temp/1490677947584.jpg
                                                                       at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
                                                                       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                                                                       at com.jph.takephoto.uitl.TUriParse.getUriForFile(TUriParse.java:87)
                                                                       at com.jph.takephoto.uitl.TUriParse.convertFileUriToFileProviderUri(TUriParse.java:41)
                                                                       at com.jph.takephoto.app.TakePhotoImpl.onPickFromCapture(TakePhotoImpl.java:360)
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
                                                                       at $Proxy8.onPickFromCapture(Unknown Source) 
                                                                       at com.imagepicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:43) 
                                                                       at android.app.Activity.performCreate(Activity.java:6736) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                       at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:160) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6200) 
                                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by 15609075281** [comment]
请问，你这个问题解决了吗？

**Comment by shunanlove** [comment]
时间太久了 有点忘记了 好像是设置的分辨率 相机不支持 ， 你需要设置相机支持的分辨率

**Comment by shunanlove** [comment]
@15609075281 时间太久了 有点忘记了 好像是设置的分辨率 相机不支持 ， 你需要设置相机支持的分辨率
