### ISSUE TITLE
7.0系统 与bugly fileprovider冲突 

### ISSUE THREAD

**Issue by XiaoYueBanZi** [crazycodeboy/TakePhoto#193]
在7.0系统上 与bugly的fileprovider冲突

**Comment by jack921** [comment]
我试了一般的解决方法都不行

**Comment by ZhanRu** [comment]
我找了好久，找到原因了但是没有解决办法，这里有个例子，是蒲公英和这个库冲突的解决办法：http://blog.csdn.net/R3lish/article/details/58147225，但是bugly是[fileProvider]，这个库是[fileprovider]，注意P，这个库的P不规范，是小写的，bugly是大写的。我把P大写bugly就可以但是这个库不行，小写这个库可以bugly就不行，绝了。

**Comment by ZhanRu** [comment]
没办法，把takephoto_library源码导入到项目里用了只能。修改com.jph.takephoto.uitl.TConstant的方法getFileProviderName。
public final static String getFileProviderName(Context context){
        return context.getPackageName()+".fileprovider";
    }
改为：
public final static String getFileProviderName(Context context){
        return context.getPackageName()+".fileProvider";
    }

**Comment by SomnusWu** [comment]
6.0 手机有影响么？为什么我这边拍照也崩溃。（集成了Bugly）
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                at com.jph.takephoto.uitl.TUriParse.getUriForFile(TUriParse.java:87)
                                                                at com.jph.takephoto.uitl.TUriParse.getTempUri(TUriParse.java:56)
                                                                at com.jph.takephoto.app.TakePhotoImpl.onPickFromCaptureWithCrop(TakePhotoImpl.java:380)
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
                                                                at $Proxy3.onPickFromCaptureWithCrop(Unknown Source) 
                                                                at com.yx.tjapp.tools.ImageSelectorUtils.CameraPhoto(ImageSelectorUtils.java:84) 
                                                                at com.yx.tjapp.ui.consult.ImgTxtConsultActivity$3.onClick(ImgTxtConsultActivity.java:129) 
                                                                at com.yx.tjapp.weight.MYLSheetDialog$2.onClick(MYLSheetDialog.java:210) 
                                                                at android.view.View.performClick(View.java:5267) 
                                                                at android.view.View$PerformClick.run(View.java:21540) 
                                                                at android.os.Handler.handleCallback(Handler.java:815) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5710) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by ZhanRu** [comment]
@SomnusWu 有，也会冲突 ...

**Comment by SomnusWu** [comment]
@ZhanRu  解决了 就是按照你们提供的解决方案  ，ths.

**Comment by ZhanRu** [comment]
@SomnusWu 希望作者以后修复这块。

**Comment by jianfeng318** [comment]
7.0系统在bugly上冲突还是没解决,作者

**Comment by liuyuttkx** [comment]
http://blog.csdn.net/liuyu0915/article/details/72621905
您们可以看下这个博客, 看是否对您们有帮助

**Comment by ZhanRu** [comment]
@liuyuttkx 3Q !
