### ISSUE TITLE
红米手机选择图片出错

### ISSUE THREAD

**Issue by PontonMao** [crazycodeboy/TakePhoto#194]
型号：Redmi Note 3
Android版本：5.0.2 LRX22G
MIUI版本：MIUI8.1|稳定版 8.1.3.0(LHNCNDI)

调用4.0.3版本
getTakePhoto().onPickFromDocumentsWithCrop(TUriParse.getTempUri(this), cropOptions);
就报错，下载demo 运行也报错

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jph.simple/com.jph.simple.ResultActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.access$800(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at java.io.File.fixSlashes(File.java:185)
	at java.io.File.<init>(File.java:134)
	at com.jph.simple.ResultActivity.showImg(ResultActivity.java:59)
	at com.jph.simple.ResultActivity.onCreate(ResultActivity.java:44)
	at android.app.Activity.performCreate(Activity.java:5975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more

应用回调是takeCancel()，但是小米的相册就弹窗 很抱歉，“相册”已停止运行

**Comment by Demarcia-cn** [comment]
魅族pro6也有同样的情况，release版，起初猜测可能是图片剪切工具的混淆问题，但是研究了半天，没有找到真正的原因。

**Comment by PontonMao** [comment]
@Demarcia-cn 
问题解决没有再报错误
我将 CropOptions的裁切工具设置setWithOwnCrop(true)， 就是用的TakePhoto自带的，不能用手机系统的，不知道原因

**Comment by Demarcia-cn** [comment]
@PontonMao 好吧，我的现在设置为false，之前ture直接crash，错误信息和你上面的一样。研究中。。。
