### ISSUE TITLE
7.1.1 小米5S拍照返回闪退

### ISSUE THREAD

**Issue by Eric-kongkong** [crazycodeboy/TakePhoto#195]
FATAL EXCEPTION: main
                                                                                Process: com.sun3d.culturalShanghaRadio, PID: 21413
                                                                                java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6709, result=-1, data=Intent { (has extras) }} to activity {com.sun3d.culturalShanghaRadio/com.sun3d.culturalShanghaRadio.mvp.view.AddImgActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3723)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3766)
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:153)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                                 Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                                    at $Proxy1.onActivityResult(Unknown Source)
                                                                                    at com.sun3d.culturalShanghaRadio.base.BaseMvpTakePhoneActivity.onActivityResult(BaseMvpTakePhoneActivity.java:45)
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6537)
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3719)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3766) 
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                                    at $Proxy1.onActivityResult(Unknown Source) 
                                                                                    at com.sun3d.culturalShanghaRadio.base.BaseMvpTakePhoneActivity.onActivityResult(BaseMvpTakePhoneActivity.java:45) 
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6537) 
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3719) 
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3766) 
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                                 Caused by: java.lang.NullPointerException: println needs a message
                                                                                    at android.util.Log.println_native(Native Method)
                                                                                    at android.util.Log.i(Log.java:160)
                                                                                    at com.sun3d.culturalShanghaRadio.util.ContentUtil.makeLog(ContentUtil.java:39)
                                                                                    at com.sun3d.culturalShanghaRadio.mvp.view.AddImgActivity.takeSuccess(AddImgActivity.java:214)
                                                                                    at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(TakePhotoImpl.java:468)
                                                                                    at com.jph.takephoto.app.TakePhotoImpl.takeResult(TakePhotoImpl.java:411)
                                                                                    at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:197)
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
                                                                                    at $Proxy1.onActivityResult(Unknown Source) 
                                                                                    at com.sun3d.culturalShanghaRadio.base.BaseMvpTakePhoneActivity.onActivityResult(BaseMvpTakePhoneActivity.java:45) 
                                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6537) 
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3719) 
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3766) 
                                                                                    at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458)

**Comment by Eric-kongkong** [comment]
出现场景是连续两次拍照后出现的

**Comment by Eric-kongkong** [comment]
已自行解决 需要在onResume里 调用takePhoto=getTakePhoto();
以执行TakePhotoInvocationHandler.of(this).bind(new TakePhotoImpl(this,this));重新绑定
找死我了T-T 清明节前最后一个下班
