### ISSUE TITLE
不裁剪，选择图片确定后闪退

### ISSUE THREAD

**Issue by xusheng927** [crazycodeboy/TakePhoto#198]
FATAL EXCEPTION: main java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66544, result=-1, data=Intent { (has extras) }} to activity {com.dahai.yixiu/com.dahai.yixiu.activity.MainActivity}: java.lang.reflect.UndeclaredThrowableException
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3343)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3386)
   at android.app.ActivityThread.access$1100(ActivityThread.java:141)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:5069)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.UndeclaredThrowableException
   at $Proxy5.onActivityResult(Native Method)
   at com.dahai.yixiu.fragment.M4MineFragment.onActivityResult(M4MineFragment.java:350)
   at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
   at android.app.Activity.dispatchActivityResult(Activity.java:5293)
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3339)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3386) 
   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:137) 
   at android.app.ActivityThread.main(ActivityThread.java:5069) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
   at $Proxy5.onActivityResult(Native Method) 
   at com.dahai.yixiu.fragment.M4MineFragment.onActivityResult(M4MineFragment.java:350) 
   at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164) 
   at android.app.Activity.dispatchActivityResult(Activity.java:5293) 
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3339) 
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3386) 
   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:137) 
   at android.app.ActivityThread.main(ActivityThread.java:5069) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NoClassDefFoundError: rx.internal.operators.OnSubscribeFromCallable
   at rx.Observable.fromCallable(Observable.java:2099)
   at me.shaohui.advancedluban.LubanCompresser.singleAction(LubanCompresser.java:40)
   at me.shaohui.advancedluban.Luban.asObservable(Luban.java:178)
   at me.shaohui.advancedluban.Luban.launch(Luban.java:129)
   at com.jph.takephoto.compress.CompressWithLuBan.compressOne(CompressWithLuBan.java:64)
   at com.jph.takephoto.compress.CompressWithLuBan.compress(CompressWithLuBan.java:52)
   at com.jph.takephoto.app.TakePhotoImpl.takeResult(TakePhotoImpl.java:436)
   at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:243)
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
   at $Proxy5.onActivityResult(Native Method) 
   at com.dahai.yixiu.fragment.M4MineFragment.onActivityResult(M4MineFragment.java:350) 
   at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164) 
   at android.app.Activity.dispatchActivityResult(Activity.java:5293) 
   at android.app.ActivityThread.deliverResults(ActivityThread.java:3339) 
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3386) 
   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:137) 
   at android.app.ActivityThread.main(ActivityThread.java:5069) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
   at dalvik.system.NativeStart.main(Native Method)

**Comment by Honsec** [comment]
你可能是访问了 外部存储的图片。
我也同样的问题。正在找解决方案。
真实的log是
` java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3632-3865/DCIM/Camera/20170324_212834.jpg
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.jph.takephoto.uitl.TUtils.convertImageToUri(TUtils.java:46)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:232)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at $Proxy3.onActivityResult(Unknown Source)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.aresjoy.socialdonate.view.ContentsWriteActivity.onActivityResult(ContentsWriteActivity.java:269)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7165)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:5000)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5047)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:229)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7331)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-07 14:31:42.765 19745-19745/com.celeblockscreen.leesangjun W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by denglihua90** [comment]
解决了吗？  请教解决方案
