### ISSUE TITLE
FileProvider问题，导致和其他第三方库冲突，建议修正。

### ISSUE THREAD

**Issue by ZhanRu** [crazycodeboy/TakePhoto#216]
大部分的第三库中FileProvider会声明为[android:authorities="${applicationId}.file**P**rovider"]，这个库的声明是[android:authorities="${applicationId}.file**p**rovider"]，其中这个库的fileProvider的P是小写，导致即使手动合并FileProvider文件，也会因为指向不同而无法兼容第三方库，如：Bugly，因为此库中com.jph.takephoto.uitl.TConstant类的getFileProviderName方法里写的是小写的**p**。
希望作者能将com.jph.takephoto.uitl.TConstant类的getFileProviderName方法中的**p**改为大写并修改AndroidManifest.xml中的[android:authorities="${applicationId}.file**p**rovider"]为[android:authorities="${applicationId}.file**P**rovider"]。

**Comment by SomnusWu** [comment]
6.0 手机有影响么？为什么我这边拍照也崩溃。（集成了Bugly）
红米Note4 , 6.0  MIUI 8.2 
这个方法报错 ：  takePhoto.onPickFromCaptureWithCrop(imageUri, getCropOptions());


   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                at com.jph.takephoto.uitl.TUriParse.getUriForFile(TUriParse.java:87)
                                                                at com.jph.takephoto.uitl.TUriParse.getTempUri(TUriParse.java:56)
                                                                at com.jph.takephoto.app.TakePhotoImpl.onPickFromCaptureWithCrop(TakePhotoImpl.java:380)
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
                                                                at $Proxy3.onPickFromCaptureWithCrop(Unknown Source) 
                                                                at com.yx.tjapp.tools.ImageSelectorUtils.CameraPhoto(ImageSelectorUtils.java:84) 
                                                                at com.yx.tjapp.ui.consult.ImgTxtConsultActivity$3.onClick(ImgTxtConsultActivity.java:129) 
                                                                at com.yx.tjapp.weight.MYLSheetDialog$2.onClick(MYLSheetDialog.java:210) 
                                                                at android.view.View.performClick(View.java:5267) 
                                                                at android.view.View$PerformClick.run(View.java:21540) 
                                                                at android.os.Handler.handleCallback(Handler.java:815) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5710) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by SomnusWu** [comment]
额， 第一次授权的时候 2次授权 都通过 ，但是会toast . 弹出提示说 没有sd卡权限 和 拍照权限 。

**Comment by SomnusWu** [comment]
就是这个原因引起的。Issues #193

**Comment by XiaoYueBanZi** [comment]
这个下载源码 在源码里改一下就好啦

**Comment by liuyuttkx** [comment]
http://blog.csdn.net/liuyu0915/article/details/72621905
可以自定义一个provider, 不用改原码, 解决bugly与之冲突问题

**Comment by ZhanRu** [comment]
@liuyuttkx 3Q !
