### ISSUE TITLE
在华为p7上点击activity中使用，点击从文件选择，选择图片选择之后点击确定，程序出现崩溃

### ISSUE THREAD

**Issue by wublack** [crazycodeboy/TakePhoto#22]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1008, result=-1, data=Intent { (has extras) }} to activity {com.jph.simple/com.jph.simple.SimpleActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3822)
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3865)
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:159)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
                                                                 Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                    at $Proxy3.onActivityResult(Unknown Source)
                                                                    at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42)
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6303)
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3818)
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3865) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:159) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5569) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                    at $Proxy3.onActivityResult(Unknown Source) 
                                                                    at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42) 
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6303) 
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3818) 
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3865) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:159) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5569) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726) 
                                                                 Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /system/media/Pre-loaded/Pictures/Picture_08_Penguins.jpg
                                                                    at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:678)
                                                                    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)
                                                                    at com.jph.takephoto.uitl.TUtils.convertImageToUri(TUtils.java:46)
                                                                    at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:230)
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
                                                                    at $Proxy3.onActivityResult(Unknown Source) 
                                                                    at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42) 
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6303) 
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3818) 
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3865) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:159) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5569) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by crazycodeboy** [comment]
在v3.0.2中已支持，` compile 'com.jph.takephoto:takephoto_library:3.0.2'`

**Comment by clunyes** [comment]
4.0.3又有这个问题了
