### ISSUE TITLE
华为 7.0，htc 6.0 版本调用相机拍照完成后啥也没有，6.0以下正常，

### ISSUE THREAD

**Issue by chenjidong** [crazycodeboy/TakePhoto#237]
具体机型 我忘记了，回头我补下

**Comment by haoyuexiyu** [comment]
好像华为拍照的7.0以上的都不行  huawei bln-al10 
[java.io.FileNotFoundException: /files_root/Crop1511234943805.jpg (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:99)
    at android.media.ExifInterface.<init>(ExifInterface.java:1116)
    at com.jph.takephoto.uitl.ImageRotateUtil.getBitmapDegree(ImageRotateUtil.java:66)
    at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:41)
    at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:177)

11-21 11:29:14.591 15721-15721/org.chuangpai.e.shop W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
    at java.lang.reflect.Proxy.invoke(Proxy.java:813)
    at $Proxy10.onActivityResult(Unknown Source)
    at org.chuangpai.e.shop.mvp.ui.activity.ManageCreateActivity.onActivityResult(ManageCreateActivity.java:603)
    at android.app.Activity.dispatchActivityResult(Activity.java:7188)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6523)

11-21 11:29:14.591 15721-15721/org.chuangpai.e.shop W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)](url)
