### ISSUE TITLE
  java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest

### ISSUE THREAD

**Issue by Knowledgeables** [crazycodeboy/TakePhoto#240]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.benjamin.github.viewpager-2/base.apk)
                                                                                 at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:45)
                                                                                 at android.widget.AbsListView.obtainView(AbsListView.java:2367)
                                                                                 at android.widget.GridView.onMeasure(GridView.java:1065)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                                 at android.view.View.measure(View.java:19740)
                                                                                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2316)
                                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1403)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1652)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1291)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6362)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                                 at android.os.Handler.handleCallback(Handler.java:754)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:160)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6197)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by Knowledgeables** [comment]
这个本来不会出错的但是我项目上使用的是glide图片加载的  两个存在就会报错了

**Comment by lhb11** [comment]
解决了吗

**Comment by haoshili** [comment]
我也遇到了这个问题，把其中一个删掉就没有问题了

**Comment by manburenshenglu** [comment]
与别的库有冲突。。。，请问现在解决了吗

**Comment by StormKid** [comment]
怎么解决这类的问题，这种问题在写weex 插件的时候经常遇到，我现在一般都换imageloader 或者自己手写三级缓存来解决，但是glide库能不能给个好点的方式来解决这类super 依赖的问题
