### ISSUE TITLE
使用相册的Bug

### ISSUE THREAD

**Issue by li13738051517** [crazycodeboy/TakePhoto#244]
当我使用相机的时候,没有问题
但是当我使用相册的时候,我发现了一个bug

06-01 17:01:10.724 4532-4532/com.rckd E/com.rckd.utils.TakePhotoUtils:  fileFromCamera ==false 
06-01 17:01:10.725 4532-4532/com.rckd E/com.rckd.utils.TakePhotoUtils:  fileFromCamera ==false,limitNum<=1 
06-01 17:01:10.725 4532-4532/com.rckd E/com.rckd.utils.TakePhotoUtils:  fileFromCamera ==false,limitNum<=1  ,IsGallery ==true 
06-01 17:01:10.725 4532-4532/com.rckd E/com.rckd.utils.TakePhotoUtils:  fileFromCamera ==false,limitNum<=1  ,IsGallery ==true ,cropYes == true

06-01 17:01:10.757 4532-4532/com.rckd E/BaseActivity: com.rckd.base.BaseActivity onPause
06-01 17:01:10.768 4532-4665/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xcb683d20
06-01 17:01:10.791 4532-4532/? E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rckd/com.darsh.multipleimageselect.activities.AlbumSelectActivity}: java.lang.ClassCastException: android.support.design.widget.AppBarLayout cannot be cast to android.support.v7.widget.Toolbar
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750)
                                                            at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                            at android.os.Looper.loop(Looper.java:207)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                         Caused by: java.lang.ClassCastException: android.support.design.widget.AppBarLayout cannot be cast to android.support.v7.widget.Toolbar
                                                            at com.darsh.multipleimageselect.activities.AlbumSelectActivity.onCreate(AlbumSelectActivity.java:71)
                                                            at android.app.Activity.performCreate(Activity.java:6300)
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2750) 
                                                            at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                            at android.os.Looper.loop(Looper.java:207) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5966) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 

测试机型:乐视2

**Comment by li13738051517** [comment]
now  i  find , if  you  have toolbar xml ,and you dismiss the pression  it's you   ,for  example ;you hava a toolbar xml ,you hava a  view contanial in  toolbar.xml  ,you will find  errror
