### ISSUE TITLE
小米5手机运行Demo：选择不裁切，不压缩->进入选择照片页面，选择照片->点击确定->系统崩溃

### ISSUE THREAD

**Issue by Clearlee** [crazycodeboy/TakePhoto#253]
日志如下：
06-20 11:19:19.814 16585-16585/com.jph.simple E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.jph.simple, PID: 16585
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jph.simple/com.jph.simple.ResultActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                    at java.io.File.fixSlashes(File.java:183)
                                                                    at java.io.File.<init>(File.java:130)
                                                                    at com.jph.simple.ResultActivity.showImg(ResultActivity.java:59)
                                                                    at com.jph.simple.ResultActivity.onCreate(ResultActivity.java:44)
                                                                    at android.app.Activity.performCreate(Activity.java:6323)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by Clearlee** [comment]
换了个魅族手机也有这个问题

**Comment by lhb11** [comment]
解决了吗 ，我也遇到这个问题

**Comment by lala9662** [comment]
。。。。。。兄弟用别人demo好歹看看代码啊，代码里只用getCompressPath，你选了不压缩肯定空了。。。
