### ISSUE TITLE
glide 4.0版本冲突

### ISSUE THREAD

**Issue by as11051105** [crazycodeboy/TakePhoto#265]
自己的项目引入的是glide4.0.0，但 'com.darsh.multipleimageselect:multipleimageselect:1.0.4' 里面引入的是glide:3.6.0，运行的话会报错：
`java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.lungfish.ielts-1/split_lib_dependencies_apk.apk:classes103.dex)
                                                                        at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:45)
                                                                        at android.widget.AbsListView.obtainView(AbsListView.java:2379)
                                                                        at android.widget.GridView.onMeasure(GridView.java:1065)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                        at android.view.View.measure(View.java:19965)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2309)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1392)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1645)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6432)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6355)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

这个冲突如何解决？

**Comment by lhb11** [comment]
遇到同样的问题 ，怎么解决的
