### ISSUE TITLE
requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by songlong446041** [crazycodeboy/TakePhoto#273]
07-26 11:04:25.630 25241-25241/com.xingjian.android.cancan W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xingjian.android.cancan/com.soundcloud.android.crop.CropImageActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
07-26 11:04:25.630 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502)
07-26 11:04:25.630 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2562)
07-26 11:04:25.630 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:165)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.os.Looper.loop(Looper.java:179)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5672)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err: Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:321)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.Activity.requestWindowFeature(Activity.java:3812)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at com.soundcloud.android.crop.CropImageActivity.setupWindowFlags(CropImageActivity.java:87)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:74)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.Activity.performCreate(Activity.java:6481)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
07-26 11:04:25.631 25241-25241/com.xingjian.android.cancan W/System.err: 	... 9 more

**Comment by songlong446041** [comment]
求解决啊
