### ISSUE TITLE
选择相册和拍照奔溃？

### ISSUE THREAD

**Issue by Destiny01** [crazycodeboy/TakePhoto#277]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6709, result=-1, data=Intent { (has extras) }} to activity {com.tianshengdiyi.kaiyanshare/com.tianshengdiyi.kaiyanshare.ui.activity.UserInfoActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
                                                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4964)
                                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:221)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                              Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                                 at $Proxy0.onActivityResult(Unknown Source)
                                                                                 at com.tianshengdiyi.kaiyanshare.ui.activity.UserInfoActivity.onActivityResult(UserInfoActivity.java:348)
                                                                                 at android.app.Activity.dispatchActivityResult(Activity.java:7137)
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:4917)
                                                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4964) 
                                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:221) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:158) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                                 at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                                 at $Proxy0.onActivityResult(Unknown Source) 
                                                                                 at com.tianshengdiyi.kaiyanshare.ui.activity.UserInfoActivity.onActivityResult(UserInfoActivity.java:348) 
三星s5，android6.0选择相册和拍照就失败

**Comment by limuyang2** [comment]
我也是这个错误日志

**Comment by LinLshare** [comment]
看起来应该是权限获取库的问题，建议自己申请权限，或者在手机设置里直接开启对应的权限，以便测试是否为权限获取问题。

**Comment by chenqiangitHub** [comment]
和一楼一样的问题。

**Comment by chenqiangitHub** [comment]
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err: java.lang.reflect.UndeclaredThrowableException
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at $Proxy0.onActivityResult(Native Method)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.gys.android.gugu.fragment.SelectImageFragment.onActivityResult(SelectImageFragment.java:145)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:5434)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:141)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.os.Looper.loop(Looper.java:136)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5113)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at dalvik.system.NativeStart.main(Native Method)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err: Caused by: java.lang.reflect.InvocationTargetException
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err: 	... 18 more
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err: Caused by: java.lang.NullPointerException
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.jph.takephoto.model.TImage.<init>(TImage.java:30)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.jph.takephoto.model.TImage.of(TImage.java:23)
08-29 16:41:06.704 9523-9523/com.gys.android.gugu.debug W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:181)

**Comment by AlanDelip** [comment]
android升级到7.0后对权限又做了一个更新即不允许出现以file://的形式调用隐式APP，需要用共享文件的形式：content:// URI
所以通过Uri.parse生成uri的方法会导致闪退，虽然更新里说到做了适配，但是看了源码好像方法不太一样。

> if (Build.VERSION.SDK_INT < 24) {
            tmpAvatarUri = Uri.fromFile(file);
        } else {
            ContentValues contentValues = new ContentValues(1);
            contentValues.put(MediaStore.Images.Media.DATA, file.getAbsolutePath());
            tmpAvatarUri = getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, contentValues);
        }

看一看这个链接，我已经解决了，需要对SDK_INT>=24的情况做额外的uri解析
[http://blog.csdn.net/jdfkldjlkjdl/article/details/59586342](url)
