### ISSUE TITLE
出现 JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by wannoo1990** [crazycodeboy/TakePhoto#299]
进入
takePhoto= (TakePhoto) TakePhotoInvocationHandler.of(this).bind(new TakePhotoImpl(this,this));
时会出现:
 JNI ERROR (app bug): local reference table overflow (max=512)
依赖的版本是:
 compile 'com.jph.takephoto:takephoto_library:4.0.3'
...部分日志:
09-14 09:11:09.237  24872-24872/com.tugouzhong.funny A/art: art/runtime/indirect_reference_table.cc:113] JNI ERROR (app bug): local reference table overflow (max=512)
09-14 09:11:09.237] local reference table dump:
09-14 09:11:09.237]   Last 10 entries (of 512):
09-14 09:11:09.237]       511: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]       510: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]       509: 0x12d754d0 java.lang.Object[] (1 elements)
09-14 09:11:09.237]       508: 0x7665bea8 java.lang.reflect.ArtMethod
09-14 09:11:09.237]       507: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]       506: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]       505: 0x12d754b0 java.lang.Object[] (1 elements)
09-14 09:11:09.237]       504: 0x7665bea8 java.lang.reflect.ArtMethod
09-14 09:11:09.237]       503: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]       502: 0x12cb84b0 $Proxy0
09-14 09:11:09.237]   Summary:
09-14 09:11:09.237]         1 of java.lang.Class
09-14 09:11:09.237]         1 of java.lang.reflect.ArtMethod
09-14 09:11:09.237]         1 of java.lang.Class
09-14 09:11:09.237]         1 of java.lang.String
09-14 09:11:09.237]         4 of java.lang.reflect.ArtMethod (1 unique instances)
09-14 09:11:09.237]         1 of java.lang.String[] (3 elements)
09-14 09:11:09.237]       121 of java.lang.reflect.ArtMethod (1 unique instances)
09-14 09:11:09.237]         1 of java.lang.String
09-14 09:11:09.237]         1 of $Proxy0
09-14 09:11:09.237]         1 of java.lang.String
09-14 09:11:09.237]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         8 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         4 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         6 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         8 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         4 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         6 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         4 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         6 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]        10 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         4 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         3 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         6 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         7 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         1 of java.lang.Object[] (1 elements)
09-14 09:11:09.247]         2 of $Proxy0 (1 unique instances)
09-14 09:11:09.247]         2 of java.lang.Object[] (1 elements) (2 unique instances)
09-14 09:11:09.247]         1 of $Proxy0
09-14 09:11:09.247]        37 of java.lang.Object[] (1 elements) (37 unique instances)
09-14 09:11:09.247] 
09-14 09:11:09.608  24872-24872/com.tugouzhong.funny A/art: art/runtime/runtime.cc:284] Runtime aborting...
09-14 09:11:09.608] Aborting thread:
09-14 09:11:09.608] "main" prio=5 tid=1 Runnable
09-14 09:11:09.608]   | group="" sCount=0 dsCount=0 obj=0x75e1c4d8 self=0xb4f07800
09-14 09:11:09.608]   | sysTid=24872 nice=0 cgrp=apps sched=0/0 handle=0xb6f3cec8
09-14 09:11:09.608]   | state=R schedstat=( 0 0 0 ) utm=175 stm=19 core=1 HZ=100
09-14 09:11:09.608]   | stack=0xbe413000-0xbe415000 stackSize=8MB
09-14 09:11:09.608]   | held mutexes= "abort lock" "mutator lock"(shared held)
09-14 09:11:09.608]   native: #00 pc 000045d4  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
09-14 09:11:09.608]   native: #01 pc 00002e55  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
09-14 09:11:09.608]   native: #02 pc 0023f0e5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+68)
09-14 09:11:09.608]   native: #03 pc 00224637  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+146)
09-14 09:11:09.608]   native: #04 pc 00214cbb  /system/lib/libart.so (_ZN3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+22)
09-14 09:11:09.608]   native: #05 pc 00214ef9  /system/lib/libart.so (_ZN3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+324)
09-14 09:11:09.608]   native: #06 pc 002150ed  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+72)
09-14 09:11:09.608]   native: #07 pc 000a6413  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1322)
09-14 09:11:09.608]   native: #08 pc 00151def  /system/lib/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+346)
09-14 09:11:09.608]   native: #09 pc 0027fcaf  /system/lib/libart.so (artQuickProxyInvokeHandler+674)
09-14 09:11:09.608]   native: #10 pc 000a22ad  /system/lib/libart.so (art_quick_proxy_invoke_handler+12)
09-14 09:11:09.608]   native: #11 pc 001d6cd5  /system/lib/libart.so (_ZN3art6mirror9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+132)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.608]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.608]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.608]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)
09-14 09:11:09.618]   at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:36)
09-14 09:11:09.618]   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-14 09:11:09.618]   at com.jph.takephoto.app.TakePhoto.permissionNotify(TakePhoto.java:-2)

**Comment by wannoo1990** [comment]
解决了
   @Override
    public TPermissionType invoke(InvokeParam invokeParam) {
        TPermissionType type=PermissionManager.checkPermission(TContextWrap.of(this),invokeParam.getMethod());
        if(TPermissionType.WAIT.equals(type)){
            this.invokeParam=invokeParam;
        }
        return type;
    }
这个return null 就会出错
