### ISSUE TITLE
as打包以后不能使用(release)，debug出来的没有问题？？

### ISSUE THREAD

**Issue by LiuYang369** [crazycodeboy/TakePhoto#30]
1.这是打开相册时的错误： Process: com.quwy.wuyou, PID: 24695
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quwy.wuyou/com.darsh.multipleimageselect.activities.AlbumSelectActivity}: android.view.InflateException: Binary XML file line #44: Error inflating class Button
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2411)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class Button
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.a.ab.b(Unknown Source)
                                                       at android.support.v7.a.q.setContentView(Unknown Source)
                                                       at com.darsh.multipleimageselect.activities.AlbumSelectActivity.onCreate(Unknown Source)
                                                       at android.app.Activity.performCreate(Activity.java:5351)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                       at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2411) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NullPointerException
                                                       at android.support.v7.widget.af.setBackgroundDrawable(Unknown Source)
                                                       at android.view.View.setBackground(View.java:15663)
                                                       at android.view.View.<init>(View.java:3906)
                                                       at android.widget.TextView.<init>(TextView.java:642)
                                                       at android.widget.Button.<init>(Button.java:107)
                                                       at android.support.v7.widget.af.<init>(Unknown Source)
                                                       at android.support.v7.widget.af.<init>(Unknown Source)
                                                       at android.support.v7.a.aq.a(Unknown Source)
                                                       at android.support.v7.a.ab.a(Unknown Source)
                                                       at android.support.v4.view.ad.onCreateView(Unknown Source)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.a.ab.b(Unknown Source) 
                                                       at android.support.v7.a.q.setContentView(Unknown Source) 
                                                       at com.darsh.multipleimageselect.activities.AlbumSelectActivity.onCreate(Unknown Source) 
                                                       at android.app.Activity.performCreate(Activity.java:5351) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                       at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2411) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

2.这是打开相机时：
  Process: com.quwy.wuyou, PID: 24847
                                                   java.lang.ExceptionInInitializerError
                                                       at com.a.a.d.d.a.x.<init>(Unknown Source)
                                                       at com.a.a.d.d.a.w.<init>(Unknown Source)
                                                       at com.a.a.f.<init>(Unknown Source)
                                                       at com.a.a.g.a(Unknown Source)
                                                       at com.a.a.f.a(Unknown Source)
                                                       at com.a.a.i.<init>(Unknown Source)
                                                       at com.a.a.i.<init>(Unknown Source)
                                                       at com.a.a.e.m.a(Unknown Source)
                                                       at com.a.a.f.a(Unknown Source)
                                                       at com.quwy.wuyou.activity.ReleaseLostActivity.takeSuccess(Unknown Source)
                                                       at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(Unknown Source)
                                                       at com.jph.takephoto.app.TakePhotoImpl.access$000(Unknown Source)
                                                       at com.jph.takephoto.app.TakePhotoImpl$1.onCompressSuccess(Unknown Source)
                                                       at com.jph.takephoto.a.d.a(Unknown Source)
                                                       at com.jph.takephoto.a.d.a(Unknown Source)
                                                       at com.jph.takephoto.a.e.a(Unknown Source)
                                                       at com.jph.takephoto.a.h.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                       at android.os.Handler.dispatchMessage(Handler.java:103)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at java.lang.Enum$1.create(Enum.java:43)
                                                       at java.lang.Enum$1.create(Enum.java:35)
                                                       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
                                                       at java.lang.Enum.getSharedConstants(Enum.java:209)
                                                       at java.util.EnumSet.noneOf(EnumSet.java:48)
                                                       at java.util.EnumSet.of(EnumSet.java:152)
                                                       at java.util.EnumSet.of(EnumSet.java:172)
                                                       at java.util.EnumSet.of(EnumSet.java:194)
                                                       at com.a.a.d.d.a.f.<clinit>(Unknown Source)
                                                       at com.a.a.d.d.a.x.<init>(Unknown Source) 
                                                       at com.a.a.d.d.a.w.<init>(Unknown Source) 
                                                       at com.a.a.f.<init>(Unknown Source) 
                                                       at com.a.a.g.a(Unknown Source) 
                                                       at com.a.a.f.a(Unknown Source) 
                                                       at com.a.a.i.<init>(Unknown Source) 
                                                       at com.a.a.i.<init>(Unknown Source) 
                                                       at com.a.a.e.m.a(Unknown Source) 
                                                       at com.a.a.f.a(Unknown Source) 
                                                       at com.quwy.wuyou.activity.ReleaseLostActivity.takeSuccess(Unknown Source) 
                                                       at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(Unknown Source) 
                                                       at com.jph.takephoto.app.TakePhotoImpl.access$000(Unknown Source) 
                                                       at com.jph.takephoto.app.TakePhotoImpl$1.onCompressSuccess(Unknown Source) 
                                                       at com.jph.takephoto.a.d.a(Unknown Source) 
                                                       at com.jph.takephoto.a.d.a(Unknown Source) 
                                                       at com.jph.takephoto.a.e.a(Unknown Source) 
                                                       at com.jph.takephoto.a.h.run(Unknown Source) 
                                                       at android.os.Handler.handleCallback(Handler.java:808) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

问题：debug跑出来没有问题，相册，相机都能用，正式打包用(key)release就报上面的错误。而且正式打包用(key)release，不做混淆的话也没有问题？求指教？？？谢谢！！！！

**Comment by crazycodeboy** [comment]
你开启了代码混淆了吧，将下面这些包不进行混淆：   
com.jph.takephoto
com.soundcloud.android.crop
com.darsh.multipleimageselect

**Comment by LiuYang369** [comment]
-keep class com.jph.takephoto.** {*;}
-keep class com.soundcloud.android.crop.** {*;}
-keep class com.darsh.multipleimageselect.** {*;}

修改了，，但是问题依旧！！！！

**Comment by LiuYang369** [comment]
解决了问题，还是混淆的问题。
华为手机混淆必须的加上以下这些，其他不用。。
-keep class com.jph.takephoto.** {;}
-keep class com.soundcloud.android.crop.* {;}
-keep class com.darsh.multipleimageselect.* {*;}
