### ISSUE TITLE
去相册选择图片程序崩溃，不兼容最新版glide，4.1版本placeholder用法变了

### ISSUE THREAD

**Issue by wangyangke** [crazycodeboy/TakePhoto#312]
去相册选择图片程序崩溃，不兼容最新版glide，4.1版本placeholder用法变了

**Comment by wangyangke** [comment]
FATAL EXCEPTION: main
                                                                         Process: com.xinxindai.eloanmobile, PID: 8671
                                                                         java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.xinxindai.eloanmobile-1/base.apk)
                                                                             at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:45)
                                                                             at android.widget.AbsListView.obtainView(AbsListView.java:2468)
                                                                             at android.widget.GridView.onMeasure(GridView.java:1065)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                             at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6247)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6247)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6247)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6247)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6247)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
                                                                             at android.view.View.measure(View.java:19913)
                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2279)
                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1370)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1623)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6467)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:908)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:720)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:655)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:894)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

**Comment by wangyangke** [comment]
好像没有兼容最新版的glide，目前最新的版本是:4.1.1，我们项目中也是用的4.1.1，翻阅资料发现：
GlideV4变化较大的是库处理选项的方式（centerCrop()，placeholder()等）
大多数的设置已经放到了RequestOptions对象中： 
示例：

RequestOptions options = new RequestOptions()
    .centerCrop()
    .placeholder(R.drawable.placeholder)
    .error(R.drawable.error)
    .priority(Priority.HIGH)
    .diskCacheStrategy(DiskCacheStrategy.NONE);
RequestOptions一次设置之后，可以在多处使用

**Comment by wangyangke** [comment]
希望大神尽快修复下，项目快上线了，急等着用

**Comment by haoyuexiyu** [comment]
有这样的问题，短时间内不能更新的话建议把glide版本调低到4.0以下

**Comment by g19980115** [comment]
这个可以把这个项目的源码[MultipleImageSelect](https://github.com/darsh2/MultipleImageSelect)下载下来自己修改一下，TakePhoto中的图片选择用的是这个库，导入module替换掉TakePhoto中的这个依赖
```Java
compile 'com.darsh.multipleimageselect:multipleimageselect:1.0.4'
```
然后就OK了。
TakePhoto也要用源码导入。
有了源码，自己修改一下就行了

**Comment by Mycircle** [comment]
1: implementation 'org.devio.takephoto:takephoto_library:4.1.0'
2: implementation 'com.github.bumptech.glide:glide:4.7.1'(4.9.0会报错)

**Comment by ikakaxi** [comment]
```
api project(':multipleimageselect')
api("org.devio.takephoto:takephoto_library:$take_photo_version") {
  exclude module: 'multipleimageselect'
}
```
我是这样做的，同作者fork了multipleimageselect这个库，我把作者fork的这个库clone下来放到本地作为lib，然后从作者的takephoto_library库中排除库里引用的multipleimageselect，使用自己clone下来的multipleimageselect就可以了，然后自己改一下multipleimageselect里面的glide版本
