### ISSUE TITLE
Android 4.4.2在拍照成功回调时，有时会崩溃

### ISSUE THREAD

**Issue by Guangsu** [crazycodeboy/TakePhoto#318]
好像是在反射处理权限那部分，下面是详细的LOG

```
W/System.err: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1003, result=-1, data=null} to activity {/.ui.personal.TechnicianCertificationActivity}: java.lang.reflect.UndeclaredThrowableException
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3384)
W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3427)
W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:139)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5103)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: Caused by: java.lang.reflect.UndeclaredThrowableException
W/System.err:     at $Proxy2.onActivityResult(Native Method)
W/System.err:     at .ui.personal.TechnicianCertificationActivity.onActivityResult(TechnicianCertificationActivity.java:109)
W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:5467)
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3380)
W/System.err: 	... 11 more
W/System.err: Caused by: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
W/System.err: 	... 15 more
W/System.err: Caused by: java.lang.NullPointerException
W/System.err:     at java.io.File.fixSlashes(File.java:185)
W/System.err:     at java.io.File.<init>(File.java:134)
W/System.err:     at .ui.personal.TechnicianCertificationActivity.takeSuccess(TechnicianCertificationActivity.java:140)
W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(TakePhotoImpl.java:468)
W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.takeResult(TakePhotoImpl.java:411)
W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:179)
W/System.err: 	... 18 more
```

**Comment by Zhangxd77** [comment]
同是4.4.2，红米，拍照回来崩。但是我的是说又一个Drawable方法，不能再低于api21使用所以有问题，请问有解决办法吗？

**Comment by DuoLa512** [comment]
我也蹦了，感觉不是那么特别好用，还是用系统

**Comment by shesio** [comment]
系统版本

Android 4.2.1,level 17
ROM

XiaoMi/MIUI
CPU架构

armeabi-v7a

一樣出現
