### ISSUE TITLE
努比亚遇到奇葩问题，选择两次崩溃

### ISSUE THREAD

**Issue by fanhua1994** [crazycodeboy/TakePhoto#337]
Process: com.zhiweism.youerplatformparent, PID: 19817
                                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1006, result=-1, data=Intent { dat=content://media/external/images/media/52642 (has extras) }} to activity {com.zhiweism.youerplatformparent/com.zhiweism.youerplatformparent.activity.AddGrowUpRecordActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3752)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3795)
                                                                                      at android.app.ActivityThread.access$1300(ActivityThread.java:164)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:147)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5513)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:971)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
                                                                                   Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                                      at $Proxy7.onActivityResult(Unknown Source)
                                                                                      at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42)
                                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3748)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3795) 
                                                                                      at android.app.ActivityThread.access$1300(ActivityThread.java:164) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:147) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5513) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:971) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766) 
                                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                                      at $Proxy7.onActivityResult(Unknown Source) 
                                                                                      at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42) 
                                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6192) 
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3748) 
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3795) 
                                                                                      at android.app.ActivityThread.access$1300(ActivityThread.java:164) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:147) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5513) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:971) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766) 
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                      at java.io.File.fixSlashes(File.java:185)
                                                                                      at java.io.File.<init>(File.java:134)
                                                                                      at com.zhiweism.youerplatformparent.activity.AddGrowUpRecordActivity.takeSuccess(AddGrowUpRecordActivity.java:132)
                                                                                      at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(TakePhotoImpl.java:468)
                                                                                      at com.jph.takephoto.app.TakePhotoImpl.takeResult(TakePhotoImpl.java:411)

**Comment by everyoung09** [comment]
小米6也出现同样问题，选择一次没任何问题，选择两次崩溃
FATAL EXCEPTION: main
Process: com.bit.yqpay, PID: 27300
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=132078, result=-1, data=Intent { dat=content://com.miui.gallery.open/raw//storage/emulated/0/Pictures/锁屏壁纸/I01024289.jpg typ=image/jpeg flg=0x1 }} to activity {com.bit.yqpay/com.bit.yqpay.activity.UploadAuditFilesActivity}: java.lang.reflect.UndeclaredThrowableException 
at android.app.ActivityThread.deliverResults(ActivityThread.java:4355) 
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4398)
at android.app.ActivityThread.-wrap19(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6665)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.reflect.UndeclaredThrowableException
at $Proxy2.onActivityResult(Unknown Source)
at com.bit.yqpay.presenter.UploadAuditFilesFragment.onActivityResult(UploadAuditFilesFragment.java:73)
at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
at android.app.Activity.dispatchActivityResult(Activity.java:7317)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4351)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4398) 
at android.app.ActivityThread.-wrap19(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6665) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
 at java.lang.reflect.Proxy.invoke(Proxy.java:913)
at $Proxy2.onActivityResult(Unknown Source) 
at com.bit.yqpay.presenter.UploadAuditFilesFragment.onActivityResult(UploadAuditFilesFragment.java:73) 
at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151) 
at android.app.Activity.dispatchActivityResult(Activity.java:7317) 
at android.app.ActivityThread.deliverResults(ActivityThread.java:4351) 
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4398) 
at android.app.ActivityThread.-wrap19(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6665) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
Caused by: java.lang.NullPointerException
at java.io.File.<init>(File.java:282)
at com.bit.yqpay.model.UploadAuditFilesModel.uploadIDPhoto(UploadAuditFilesModel.java:29)
at com.bit.yqpay.presenter.UploadAuditFilesFragment.uploadIDPhoto(UploadAuditFilesFragment.java:205)
at com.bit.yqpay.presenter.UploadAuditFilesFragment.takeSuccess(UploadAuditFilesFragment.java:201)
at com.jph.takephoto.app.TakePhotoImpl.handleTakeCallBack(TakePhotoImpl.java:468)
at com.jph.takephoto.app.TakePhotoImpl.takeResult(TakePhotoImpl.java:411)
at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:129)
at java.lang.reflect.Method.invoke(Native Method) 
at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
at java.lang.reflect.Proxy.invoke(Proxy.java:913) 
at $Proxy2.onActivityResult(Unknown Source) 
at com.bit.yqpay.presenter.UploadAuditFilesFragment.onActivityResult(UploadAuditFilesFragment.java:73) 
at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151) 
at android.app.Activity.dispatchActivityResult(Activity.java:7317) 
at android.app.ActivityThread.deliverResults(ActivityThread.java:4351) 
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4398) 
at android.app.ActivityThread.-wrap19(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6665) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by everyoung09** [comment]
我这边解决了～是因为我压缩配置只有初始化的时候做了，实际上每次拍照或选择照片时都得设置压缩配置
