### ISSUE TITLE
小米手机调用拍照后崩溃

### ISSUE THREAD

**Issue by tony-young** [crazycodeboy/TakePhoto#39]
使用小米手机调用相机拍照后修剪，点确定后崩溃

**Comment by crazycodeboy** [comment]
使用simple试一下。
另外，如果simple依然，麻烦将手机型号，系统版本以及Android版本，还有异常log贴出

**Comment by tony-young** [comment]
能提供下simple的APK吗？我现在不太方便去弄环境

**Comment by crazycodeboy** [comment]
[https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simplerelease.apk](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simplerelease.apk)

**Comment by tony-young** [comment]
Demo里面点击拍照程序崩溃

手机型号

日志：
java.lang.IllegalStateException: Could not execute method for android:onClick
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4461)
	at android.view.View.performClick(View.java:5207)
	at android.view.View$PerformClick.run(View.java:21177)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4456)
	... 9 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at $Proxy0.c(Unknown Source)
	at com.jph.simple.a.onClick(SourceFile:98)
	at com.jph.simple.SimpleActivity.onClick(SourceFile:46)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.jph.a.d.d.invoke(SourceFile:39)
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	... 14 more
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera/.Camera clip={text/uri-list U:content://com.jph.takephoto.fileprovider/camera_photos/images/20161013_131338.jpg} (has extras) } from ProcessRecord{e9a2799 16394:com.jph.simple/u0a187} (pid=16394, uid=10187) with revoked permission android.permission.CAMERA
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2661)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
	at android.app.Activity.startActivityForResult(Activity.java:3978)
	at android.app.Activity.startActivityForResult(Activity.java:3939)
	at com.jph.a.e.e.a(SourceFile:82)
	at com.jph.a.e.e.b(SourceFile:112)
	at com.jph.a.a.d.c(SourceFile:371)
	... 17 more

**Comment by crazycodeboy** [comment]
不好意思，上面那个simple是很久之前的，用这个吧[https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by tony-young** [comment]
好的，这次好像没什么问题了，我再检查一下我自己的集成代码，谢谢
