### ISSUE TITLE
空指针CompressConfig.isEnableReserveRaw()' on a null object reference

### ISSUE THREAD

**Issue by lxp92** [crazycodeboy/TakePhoto#405]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.jph.takephoto.compress.CompressConfig.isEnableReserveRaw()' on a null object reference
	at com.jph.takephoto.app.TakePhotoImpl$1.onCompressSuccess(TakePhotoImpl.java:419)
	at com.jph.takephoto.compress.CompressImageImpl.handleCompressCallBack(CompressImageImpl.java:96)
	at com.jph.takephoto.compress.CompressImageImpl.continueCompress(CompressImageImpl.java:79)
	at com.jph.takephoto.compress.CompressImageImpl.access$000(CompressImageImpl.java:18)
	at com.jph.takephoto.compress.CompressImageImpl$1.onCompressSuccess(CompressImageImpl.java:64)
	at com.jph.takephoto.compress.CompressImageUtil$2.run(CompressImageUtil.java:137)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by ACMNexus** [comment]
我也遇到了这个问题了，而且这个问题出现的概率还挺高的，我也分析了一下代码，但是也没有想明白到底是什么原因导致空指针的。

**Comment by 790396054** [comment]
同样遇到了这个问题，之前测试没有问题，过了几天，代码没有修改，就出现这个问题了，debug 跟踪了半天，也没明白是怎么回事？

**Comment by MingForce** [comment]
同样遇到这个问题，不知怎么解决
