### ISSUE TITLE
华为荣耀6在选中图片,点击确定后出现bug

### ISSUE THREAD

**Issue by zhuzhaolin** [crazycodeboy/TakePhoto#42]
10-15 14:02:08.585 16672-16672/com.jph.simple E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.jph.simple, PID: 16672
                                                                java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66544, result=-1, data=Intent { (has extras) }} to activity {com.jph.simple/com.jph.simple.SimpleFragmentActivity}: java.lang.reflect.UndeclaredThrowableException
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3838)
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3881)
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:163)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5595)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                 Caused by: java.lang.reflect.UndeclaredThrowableException
                                                                    at $Proxy3.onActivityResult(Unknown Source)
                                                                    at com.jph.takephoto.app.TakePhotoFragment.onActivityResult(TakePhotoFragment.java:42)
                                                                    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6325)
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3834)
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3881) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:163) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                    at $Proxy3.onActivityResult(Unknown Source) 
                                                                    at com.jph.takephoto.app.TakePhotoFragment.onActivityResult(TakePhotoFragment.java:42) 
                                                                    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165) 
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6325) 
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3834) 
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3881) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:163) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                 Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/sdcard1/图片/56efdbe1193131e57f61511bda14b686.jpg
                                                                    at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:679)
                                                                    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:378)
                                                                    at com.jph.takephoto.uitl.TUtils.convertImageToUri(TUtils.java:46)
                                                                    at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:230)
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
                                                                    at $Proxy3.onActivityResult(Unknown Source) 
                                                                    at com.jph.takephoto.app.TakePhotoFragment.onActivityResult(TakePhotoFragment.java:42) 
                                                                    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165) 
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6325) 
                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3834) 
                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3881) 
                                                                    at android.app.ActivityThread.access$1700(ActivityThread.java:163) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by zhuzhaolin** [comment]
是在剪切SD卡中的图片出现问题，剪切内部存储的图片没问题。
