### ISSUE TITLE
Vivo

### ISSUE THREAD

**Issue by jasonsyf** [crazycodeboy/TakePhoto#437]
CRASH DEVICE: vivo X9Plus UNROOT
 RUNTIME AVAIL RAM:2513268736 ROM:4620197888 SD:3991052288
RUNTIME TOTAL RAM:6124527616 ROM:56865169408 SD:56236023808
 CRASH STACK: 
java.lang.reflect.UndeclaredThrowableException
    at $Proxy6.onPickFromCaptureWithCrop(Unknown Source)
    at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232)
    at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source)
    at android.view.View.performClick(View.java:5646)
    at android.view.View$PerformClick.run(View.java:22500)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6328)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
    at java.lang.reflect.Proxy.invoke(Proxy.java:813)
    at $Proxy6.onPickFromCaptureWithCrop(Unknown Source) 
    at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232) 
    at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source) 
    at android.view.View.performClick(View.java:5646) 
    at android.view.View$PerformClick.run(View.java:22500) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6328) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
    at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
    at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
    at com.jph.takephoto.uitl.TUriParse.getUriForFile(TUriParse.java:87)
    at com.jph.takephoto.uitl.TUriParse.getTempUri(TUriParse.java:56)
    at com.jph.takephoto.app.TakePhotoImpl.onPickFromCaptureWithCrop(TakePhotoImpl.java:380)
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
    at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
    at $Proxy6.onPickFromCaptureWithCrop(Unknown Source) 
    at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232) 
    at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source) 
    at android.view.View.performClick(View.java:5646) 
    at android.view.View$PerformClick.run(View.java:22500) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6328) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by jasonsyf** [comment]
# CRASH DEVICE: vivo X9Plus UNROOT
    # RUNTIME AVAIL RAM:2513268736 ROM:4620197888 SD:3991052288
    # RUNTIME TOTAL RAM:6124527616 ROM:56865169408 SD:56236023808
    # CRASH STACK: 
    java.lang.reflect.UndeclaredThrowableException
        at $Proxy6.onPickFromCaptureWithCrop(Unknown Source)
        at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232)
        at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22500)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6328)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy6.onPickFromCaptureWithCrop(Unknown Source) 
        at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232) 
        at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source) 
        at android.view.View.performClick(View.java:5646) 
        at android.view.View$PerformClick.run(View.java:22500) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6328) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
        at com.jph.takephoto.uitl.TUriParse.getUriForFile(TUriParse.java:87)
        at com.jph.takephoto.uitl.TUriParse.getTempUri(TUriParse.java:56)
        at com.jph.takephoto.app.TakePhotoImpl.onPickFromCaptureWithCrop(TakePhotoImpl.java:380)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
        at $Proxy6.onPickFromCaptureWithCrop(Unknown Source) 
        at com.sinotech.modulemain.me.PersonalFragment$2.lambda$setData$0$PersonalFragment$2(PersonalFragment.java:232) 
        at com.sinotech.modulemain.me.PersonalFragment$2$$Lambda$0.onClick(Unknown Source) 
        at android.view.View.performClick(View.java:5646) 
        at android.view.View$PerformClick.run(View.java:22500) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6328) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
