### ISSUE TITLE
在三星S9, 坚果pro2上面选择图片出现崩溃

### ISSUE THREAD

**Issue by wwxwwq** [crazycodeboy/TakePhoto#457]
09-12 10:55:28.149 5534-5534/org.devio.simple E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.devio.simple, PID: 5534
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1008, result=-1, data=Intent { (has extras) }} to activity {org.devio.simple/org.devio.simple.SimpleActivity}: java.lang.reflect.UndeclaredThrowableException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4308)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4351)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy0.onActivityResult(Unknown Source)
        at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42)
        at android.app.Activity.dispatchActivityResult(Activity.java:7105)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4304)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4351) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6385) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy0.onActivityResult(Unknown Source) 
        at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42) 
        at android.app.Activity.dispatchActivityResult(Activity.java:7105) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4304) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4351) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6385) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) 
     Caused by: java.lang.StringIndexOutOfBoundsException: length=13; index=-1
        at java.lang.String.substring(String.java:1933)
        at com.jph.takephoto.uitl.TImageFiles.getMimeTypeByFileName(TImageFiles.java:138)
        at com.jph.takephoto.uitl.TImageFiles.getMimeType(TImageFiles.java:133)
        at com.jph.takephoto.uitl.TImageFiles.getTempFile(TImageFiles.java:96)
        at com.jph.takephoto.model.MultipleCrop.<init>(MultipleCrop.java:31)
        at com.jph.takephoto.model.MultipleCrop.of(MultipleCrop.java:22)
        at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:237)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
        at $Proxy0.onActivityResult(Unknown Source) 
        at com.jph.takephoto.app.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:42) 
        at android.app.Activity.dispatchActivityResult(Activity.java:7105) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4304) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4351) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6385) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) 
    
用官方的demo运行也是同样的崩溃，选择的图片是在淘宝旺旺聊天直接拍的，图片地址是/Storage/Android/data/com.taobao.****/，属于淘宝app私有空间的图片，但图片是能被相册扫描到；

**Comment by wwxwwq** [comment]
是4.0.3版本，手机版本是7.1.1，坚果pro2，自己的项目出现这个崩溃，然后运行官方demo也是同样的崩溃，选择相册里面非三方app的图片是正常的；

**Comment by wwxwwq** [comment]
找到原因了：TakePhoto/takephoto_library/src/main/java/org/devio/takephoto/uitl/TImageFiles.java
这个文件下的getMimeTypeByFileName方法有问题，没有考虑到没有后缀的图片，没做兼容处理，导致越界；
public static String getMimeTypeByFileName(String fileName) {
        return fileName.substring(fileName.lastIndexOf("."), fileName.length());
    }
现在很多三方app拍照或下载的图片会以时间戳或是md5值直接当文件名，不带后缀，而且广播通知相册扫描，导致在相册中可以看到这种没有后缀名的图片；
