### ISSUE TITLE
NullPointerException 这段代码出现空指针

### ISSUE THREAD

**Issue by shanhaojie** [crazycodeboy/TakePhoto#482]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.darsh.multipleimageselect.adapters.CustomGenericAdapter.getCount(CustomGenericAdapter.java:27)

**Comment by lshl2015** [comment]
the same crash !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.darsh.multipleimageselect.adapters.CustomGenericAdapter.getCount(CustomGenericAdapter.java:27)
	at com.baidu.mobstat.bq.a(SourceFile:1429)
	at com.baidu.mobstat.ba.a(SourceFile:1593)
	at com.baidu.mobstat.ba.a(SourceFile:717)
	at com.baidu.mobstat.ba.b(SourceFile:230)
	at com.baidu.mobstat.ba.b(SourceFile:35)
	at com.baidu.mobstat.ba$6.run(SourceFile:210)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:185)
	at android.os.HandlerThread.run(HandlerThread.java:61)
