### ISSUE TITLE
 Failure delivering result ResultInfo{who=null, request=1006, result=-1, data=Intent { dat=content://com.miui.gallery.open/raw//storage/emulated/0/DCIM/Camera/IMG_20181225_104718.jp

### ISSUE THREAD

**Issue by liupeng1991** [crazycodeboy/TakePhoto#484]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1006, result=-1, data=Intent { dat=content://com.miui.gallery.open/raw//storage/emulated/0/DCIM/Camera/IMG_20181225_104718.jpg typ=image/jpeg flg=0x1 }} to activity {com.lp.oapp/com.lp.oapp.usermanager.activity.UserPhotoActivity}: java.lang.reflect.UndeclaredThrowableException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4296)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4340)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
     Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy2.onActivityResult(Unknown Source)
        at com.lp.oapp.usermanager.activity.UserPhotoActivity.onActivityResult(UserPhotoActivity.java:352)
        at android.app.Activity.dispatchActivityResult(Activity.java:7348)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4292)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4340) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6600) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by dary123** [comment]
同问

**Comment by zrzhong** [comment]
我也遇到了，我的问题是#takeSuccess的时候调用了result.getImage().getCompressPath()拿到图片地址，然而我的设置里面没有设置压缩，所以拿到的是空的图片地址，检查下你们是否启用了压缩

**Comment by dary123** [comment]
> 我也遇到了，我的问题是#takeSuccess的时候调用了result.getImage().getCompressPath()拿到图片地址，然而我的设置里面没有设置压缩，所以拿到的是空的图片地址，检查下你们是否启用了压缩

都是取的原图，没有取压缩
