### ISSUE TITLE
打开相册报错了

### ISSUE THREAD

**Issue by zjycpzjy** [crazycodeboy/TakePhoto#531]
打开相册报错了

**Comment by liangxiwei** [comment]
LOG都没有。。

**Comment by tendoasan** [comment]
@zjiayingok @liangxiwei 我这边也发现报错了，日志如下：
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager'
at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:45)
        at android.widget.AbsListView.obtainView(AbsListView.java:2388)
        at android.widget.GridView.onMeasure(GridView.java:1065)
        at android.view.View.measure(View.java:22097)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
        at android.view.View.measure(View.java:22097)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2467)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1806)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by tendoasan** [comment]
参考 https://github.com/crazycodeboy/TakePhoto/issues/419 的解决方法，可以正常打开相册
