### ISSUE TITLE
魅蓝手机oom

### ISSUE THREAD

**Issue by fuhongjie** [crazycodeboy/TakePhoto#59]
11-04 09:31:40.590 E/AndroidRuntime(21862): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 51121164 byte allocation with 16777120 free bytes and 46MB until OOM

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:838)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:814)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:474)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:508)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:42)

11-04 09:31:40.590 E/AndroidRuntime(21862): 	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:157)

**Comment by crazycodeboy** [comment]
在做什么操作是发生的？
