### ISSUE TITLE
release包, 相机,直接crash

### ISSUE THREAD

**Issue by yangxiaoge** [crazycodeboy/TakePhoto#83]
11-18 11:20:24.596 12553-12553/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ztesoft.zsmart.datamall.app.mpt, PID: 12553
                                                   java.lang.reflect.UndeclaredThrowableException
                                                       at $Proxy2.a(Unknown Source)
                                                       at com.ztesoft.zsmart.datamall.app.ui.fragment.my.MyProfileFragment$4.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:5609)
                                                       at android.view.View$PerformClick.run(View.java:22262)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(Unknown Source)
                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                       at $Proxy2.a(Unknown Source) 
                                                       at com.ztesoft.zsmart.datamall.app.ui.fragment.my.MyProfileFragment$4.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:5609) 
                                                       at android.view.View$PerformClick.run(View.java:22262) 
                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                    Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list U:content://com.ztesoft.zsmart.datamall.app.mpt.fileprovider/camera_photos/storage/emulated/0/mpt_pic/camera_image.jpg} (has extras) } from ProcessRecord{c5ad4d7 12553:com.ztesoft.zsmart.datamall.app.mpt/u0a130} (pid=12553, uid=10130) with revoked permission android.permission.CAMERA
                                                       at android.os.Parcel.readException(Parcel.java:1683)
                                                       at android.os.Parcel.readException(Parcel.java:1636)
                                                       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3071)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
                                                       at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(Unknown Source)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
                                                       at android.support.v4.app.ActivityCompatJB.startActivityForResult(Unknown Source)
                                                       at android.support.v4.app.ActivityCompat.startActivityForResult(Unknown Source)
                                                       at android.support.v4.app.FragmentActivity.startActivityFromFragment(Unknown Source)
                                                       at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(Unknown Source)
                                                       at android.support.v4.app.Fragment.startActivityForResult(Unknown Source)
                                                       at android.support.v4.app.Fragment.startActivityForResult(Unknown Source)
                                                       at com.jph.takephoto.uitl.TUtils.a(Unknown Source)
                                                       at com.jph.takephoto.uitl.TUtils.b(Unknown Source)
                                                       at com.jph.takephoto.app.TakePhotoImpl.a(Unknown Source)
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(Unknown Source) 
                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
                                                       at $Proxy2.a(Unknown Source) 
                                                       at com.ztesoft.zsmart.datamall.app.ui.fragment.my.MyProfileFragment$4.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:5609) 
                                                       at android.view.View$PerformClick.run(View.java:22262) 
                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by teemoleary** [comment]
你确定是混淆文件的原因？可是我加了还是会报这个错误啊

**Comment by zhizhulp** [comment]
同样的问题

**Comment by zhizhulp** [comment]
混淆改为这个
-keep class org.devio.takephoto.** { *; }
-dontwarn org.devio.takephoto.**
