### ISSUE TITLE
三星Galaxy Note ||   系统4.3  上传压缩图片过程中出现问题

### ISSUE THREAD

**Issue by jiaqq** [crazycodeboy/TakePhoto#95]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1003, result=-1, data=null} to activity {shenzhen.com.cn/shenzhen.com.cn.company.CertificationActivity}: java.lang.reflect.UndeclaredThrowableException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3544)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3587)
	at android.app.ActivityThread.access$1200(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at $Proxy1.onActivityResult(Native Method)
	at com.jph.takephoto.app.TakePhotoFragmentActivity.onActivityResult(TakePhotoFragmentActivity.java:41)
	at android.app.Activity.dispatchActivityResult(Activity.java:5563)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3540)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
	... 15 more
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
	at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:42)
	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:175)
	... 18 more
java.lang.reflect.UndeclaredThrowableException
	at $Proxy1.onActivityResult(Native Method)
	at com.jph.takephoto.app.TakePhotoFragmentActivity.onActivityResult(TakePhotoFragmentActivity.java:41)
	at android.app.Activity.dispatchActivityResult(Activity.java:5563)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3540)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3587)
	at android.app.ActivityThread.access$1200(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
	... 15 more
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
	at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:42)
	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:175)
	... 18 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
	at $Proxy1.onActivityResult(Native Method)
	at com.jph.takephoto.app.TakePhotoFragmentActivity.onActivityResult(TakePhotoFragmentActivity.java:41)
	at android.app.Activity.dispatchActivityResult(Activity.java:5563)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3540)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3587)
	at android.app.ActivityThread.access$1200(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
	at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:42)
	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:175)
	... 18 more
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
	at com.jph.takephoto.uitl.ImageRotateUtil.correctImage(ImageRotateUtil.java:42)
	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:175)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
	at $Proxy1.onActivityResult(Native Method)
	at com.jph.takephoto.app.TakePhotoFragmentActivity.onActivityResult(TakePhotoFragmentActivity.java:41)
	at android.app.Activity.dispatchActivityResult(Activity.java:5563)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3540)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3587)
	at android.app.ActivityThread.access$1200(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by crazycodeboy** [comment]
三星手机拍照的照片通常会有旋转角度问题，TakePhoto加入了自动纠正旋转角度的功能，在纠正旋转照片时需要将照片读到内存，所以可能会导致oom，下一版本的TakePhoto会将是否纠正旋转角度设为可选，另外，你也可以参照[获取更高的兼容性](https://github.com/crazycodeboy/TakePhoto#获取更高的兼容性)的说明，设置拍照时不旋转图片，来解决问题。
