### ISSUE TITLE
 Nexus6相册选择图片后压缩出错

### ISSUE THREAD

**Issue by loganguo** [crazycodeboy/TakePhoto#98]
Nexus6，with android7.0.
具体操作是：不裁剪，自带压缩工具压缩，显示进度条，压缩最大值102400，最大像素480.
TakePhoto版本是4.0.2

```
CompressConfig config = new CompressConfig.Builder().setMaxSize(102400).setMaxPixel(480).enableReserveRaw(true).create();
takePhoto.onEnableCompress(config, true);
takePhoto.onPickFromCapture(outPutUri);
```
同样的设置，运行demo没问题，但是在我的应用中报错。
错误是
```
: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1003, result=-1, data=Intent {  }} to activity {cn.com.package.name.debug/cn.com.package.name.ui.activity.RatingActivity}: java.lang.reflect.UndeclaredThrowableException
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1003, result=-1, data=Intent {  }} to activity {cn.com.package.name.debug/cn.com.package.name.ui.activity.RatingActivity}: java.lang.reflect.UndeclaredThrowableException
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3374)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	... 10 more
11-30 18:47:39.973  9468  9468 E AndroidRuntime: Caused by: java.lang.reflect.UndeclaredThrowableException
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at $Proxy1.onActivityResult(Unknown Source)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at cn.com.package.name.ui.activity.RatingActivity.onActivityResult(RatingActivity.java:458)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6917)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	... 11 more
11-30 18:47:39.973  9468  9468 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at com.jph.takephoto.model.TImage.<init>(TImage.java:30)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at com.jph.takephoto.model.TImage.of(TImage.java:23)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:181)
11-30 18:47:39.973  9468  9468 E AndroidRuntime: 	... 20 more
```

**Comment by lianhuo** [comment]
请问 解决了吗？
